### ISSUE TITLE
Question about BCE

### ISSUE THREAD

**Issue by AlanChou** [vikasverma1077/manifold_mixup#7]
Hi,

I would like to know the reason of using BCE instead of CrossEntropy. Is this critical to Manifold Mixup? Is this also the reason you train 2000 epochs which is much longer than the common training schedules?

**Comment by alexmlamb** [comment]
"I would like to know the reason of using BCE instead of CrossEntropy. Is this critical to Manifold Mixup?"

 Is this also the reason you train 2000 epochs which is much longer than the common training schedules?

**Comment by AlanChou** [comment]
Thank you very much for the super fast reply !
