### ISSUE TITLE
Question about accuracy during Training

### ISSUE THREAD

**Issue by saikalyan9981** [vikasverma1077/manifold_mixup#9]
I was trying to implement mix-up-hidden for preactresnet18, I found that for calculating accuracy you are comparing mix-up output with original target instead of re-weighted one, that makes accuracy low during training, I didn't understand what that accuracy signifies/implies?

**Comment by vikasverma1077** [comment]
It does not imply anything during training. You should look at the training
loss. We can not use the reweighted targets because for computing the
accuracy we need discrete targets.
